# Generated by Django 6.0.1 on 2026-03-20 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('zip_code', models.TextField()),
                ('street_name', models.TextField()),
                ('dob', models.DateField()),
                ('party', models.CharField(max_length=1)),
                ('year_participation', models.BooleanField(default=False)),
            ],
        ),
    ]
