# Generated by Django 6.0.1 on 2026-03-20 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='dob',
            new_name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='party',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='year_participation',
        ),
        migrations.AddField(
            model_name='voter',
            name='apartment_number',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='date_of_registration',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='party_affiliation',
            field=models.CharField(default='', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='precinct_number',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='street_number',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='v20state',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='v21primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='v21town',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='v22general',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='v23town',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='voter',
            name='voter_id',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voter',
            name='voter_score',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
