# Generated by Django 6.0.1 on 2026-03-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0003_remove_photo_image_url_photo_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
