# Generated by Django 6.0.1 on 2026-03-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0004_alter_photo_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='photo',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
