# Generated by Django 6.0.4 on 2026-04-29 21:50

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('patient_alias', models.CharField(help_text='Anonymized name used for this case', max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('sex', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Prefer not to say', 'Prefer not to say')], max_length=30)),
                ('case_status', models.CharField(choices=[('Open', 'Open'), ('Investigating', 'Investigating'), ('Resolved', 'Resolved')], default='Open', max_length=20)),
                ('chief_complaint', models.CharField(max_length=255)),
                ('date_started', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Hormonal', 'Hormonal'), ('Metabolic', 'Metabolic'), ('Reproductive', 'Reproductive'), ('Autoimmune', 'Autoimmune'), ('Nutritional', 'Nutritional'), ('Infectious', 'Infectious'), ('Other', 'Other')], default='Other', max_length=50)),
                ('description', models.TextField()),
                ('common_age_group', models.CharField(blank=True, max_length=100)),
                ('red_flag_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Low', max_length=20)),
                ('typical_duration', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('body_system', models.CharField(choices=[('Reproductive', 'Reproductive'), ('Endocrine', 'Endocrine'), ('Digestive', 'Digestive'), ('Neurological', 'Neurological'), ('Skin', 'Skin'), ('Cardiovascular', 'Cardiovascular'), ('General', 'General'), ('Other', 'Other')], default='Other', max_length=50)),
                ('description', models.TextField()),
                ('is_common', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence_score', models.PositiveIntegerField(help_text='Enter a value from 0 to 100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('status', models.CharField(choices=[('Possible', 'Possible'), ('Likely', 'Likely'), ('Ruled Out', 'Ruled Out'), ('Confirmed', 'Confirmed')], default='Possible', max_length=20)),
                ('reasoning_notes', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='possible_conditions', to='project.case')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_cases', to='project.condition')),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(choices=[('General Practice', 'General Practice'), ('Internal Medicine', 'Internal Medicine'), ('Endocrinology', 'Endocrinology'), ('Gynecology', 'Gynecology'), ('Neurology', 'Neurology'), ('Cardiology', 'Cardiology'), ('Other', 'Other')], default='General Practice', max_length=50)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='project.doctorprofile'),
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('Lab Result', 'Lab Result'), ('Family History', 'Family History'), ('Lifestyle Factor', 'Lifestyle Factor'), ('Medication History', 'Medication History'), ('Cycle History', 'Cycle History'), ('Physical Exam', 'Physical Exam'), ('Other', 'Other')], default='Other', max_length=30)),
                ('description', models.TextField()),
                ('value_text', models.CharField(blank=True, help_text='e.g. lab value or measurement', max_length=255)),
                ('date_recorded', models.DateField(default=django.utils.timezone.now)),
                ('supports_condition', models.CharField(blank=True, max_length=100)),
                ('contradicts_condition', models.CharField(blank=True, max_length=100)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='project.case')),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('sex', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Prefer not to say', 'Prefer not to say')], default='Prefer not to say', max_length=30)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to='project.patientprofile'),
        ),
        migrations.CreateModel(
            name='CaseSymptom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.PositiveIntegerField(help_text='Rate from 1 (very mild) to 10 (severe)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('frequency', models.CharField(choices=[('Daily', 'Daily'), ('Weekly', 'Weekly'), ('Occasional', 'Occasional')], default='Occasional', max_length=20)),
                ('date_noticed', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_symptoms', to='project.case')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptom_cases', to='project.symptom')),
            ],
        ),
    ]
